# Generated by Django 6.1 on 2026-08-27 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('idAutor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaNac', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('idObra', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('fechaPublicacion', models.DateField(blank=True, null=True)),
                ('signatura', models.CharField(max_length=50, unique=True)),
                ('autores', models.ManyToManyField(related_name='obras', to='catalogo.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Grabacion',
            fields=[
                ('obra_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogo.obra')),
                ('ean', models.CharField(max_length=13, unique=True)),
                ('soporte', models.CharField(choices=[('CD', 'CD'), ('DVD', 'DVD'), ('BLURAY', 'Blu-ray'), ('VINILO', 'Vinilo'), ('CASETE', 'Casete'), ('VHS', 'VHS')], max_length=20)),
                ('duracion', models.DurationField()),
                ('productoraSello', models.CharField(blank=True, max_length=255)),
                ('genero', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('catalogo.obra',),
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('obra_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogo.obra')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('editorial', models.CharField(blank=True, max_length=255, null=True)),
                ('materia', models.CharField(blank=True, max_length=255, null=True)),
                ('coleccion', models.CharField(blank=True, max_length=255, null=True)),
                ('edicion', models.IntegerField(blank=True, null=True)),
            ],
            bases=('catalogo.obra',),
        ),
        migrations.CreateModel(
            name='Periodico',
            fields=[
                ('obra_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogo.obra')),
                ('issn', models.CharField(max_length=8, unique=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('edicion', models.CharField(blank=True, max_length=50, null=True)),
                ('periodicidad', models.CharField(max_length=50)),
                ('director', models.CharField(blank=True, max_length=100)),
            ],
            bases=('catalogo.obra',),
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('obra_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogo.obra')),
                ('issn', models.CharField(max_length=8, unique=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('volumen', models.IntegerField(blank=True, null=True)),
                ('temporada', models.CharField(blank=True, max_length=50, null=True)),
                ('periodicidad', models.CharField(blank=True, max_length=50, null=True)),
                ('materia', models.CharField(max_length=100)),
            ],
            bases=('catalogo.obra',),
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('idEjemplar', models.AutoField(primary_key=True, serialize=False)),
                ('reservado', models.BooleanField(default=False)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejemplares', to='catalogo.obra')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField(auto_now_add=True)),
                ('fechaFin', models.DateField()),
                ('fechaDevolucion', models.DateField(blank=True, null=True)),
                ('fechaProrroga', models.DateField(blank=True, null=True)),
                ('prorrogasRestantes', models.IntegerField(default=3)),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='catalogo.ejemplar')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
