# Generated by Django 6.1.1 on 2026-09-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='fechaNac',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='edicion',
        ),
        migrations.AddField(
            model_name='obra',
            name='tipo',
            field=models.CharField(choices=[('LIBRO', 'Libro'), ('REVISTA', 'Revista'), ('PERIODICO', 'Periódico'), ('GRABACION', 'Grabación')], default='LIBRO', max_length=20),
            preserve_default=False,
        ),
    ]
