# Generated by Django 6.1.1 on 2026-09-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_remove_autor_fechanac_remove_libro_edicion_obra_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='autores',
            new_name='autor',
        ),
    ]
