# Generated by Django 6.1.1 on 2026-09-24 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_rename_autores_obra_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Productora',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='grabacion',
            name='productoraSello',
        ),
        migrations.AlterField(
            model_name='libro',
            name='editorial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Libros', to='catalogo.editorial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grabacion',
            name='productora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grabaciones', to='catalogo.productora'),
        ),
    ]
