# Generated by Django 6.0.4 on 2026-05-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('shortDesc', models.CharField(max_length=20)),
                ('longDesc', models.CharField(max_length=50)),
                ('stock', models.IntegerField(default=20)),
            ],
        ),
    ]
