# Generated by Django 6.0.7 on 2026-07-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.BooleanField(blank=True, help_text='0=H, 1=M', null=True),
        ),
    ]
